apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
spec:
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: streamlit_app:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8501
        env:
        - name: API_ENDPOINT
          value: garbage-classification-model.gc.svc.cluster.local:3000/predict

